baseURL = 'https://none-word.github.io'
languageCode = 'en-us'
title = 'Inno alumni portal docs'
theme = 'hugo-book'

# Book configuration
disablePathToLower = true
enableGitInfo = true

# Needed for mermaid/katex shortcodes
[markup]
[markup.goldmark.renderer]
unsafe = true

[markup.tableOfContents]
startLevel = 1

[languages]
[languages.en]
languageName = 'English'
contentDir = 'content'
weight = 1