baseURL = 'https://okulusdev.github.io'
languageCode = 'ru'
title = 'Okulus Dev'
languageName = 'ru'
defaultContentLanguage = "ru"
paginate = 100 #frontpage pagination
theme = 'monochrome'
enableGitInfo = true

[[navbar]]
identifier = "categories"
name = "Категории"
url = "/categories/"
weight = 1
[[navbar]]
identifier = "tags"
name = "Теги"
url = "/tags/"
weight = 2
[[navbar]]
identifier = "posts"
name = "Статьи"
url = "/post/"
weight = 3

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[markup]
[markup.highlight] # подсветка кода
anchorLineNos = false
codeFences = true
guessSyntax = false
hl_Lines = ''
hl_inline = false
lineAnchors = ''
lineNoStart = 1
lineNos = false
lineNumbersInTable = true
noClasses = true
noHl = false
style = 'gruvbox' # темы можно посмотреть на https://xyproto.github.io/splash/docs/all.html
tabWidth = 4

[params]
navbar_title = "Okulus Dev" # default: site's `title`
footer = "Copyright © 2023 by OkulusDev" # default: None
enable_toc = true # default: true
enable_collapsible_toc = true # default: false
enable_collapsible_changelogs = false # default: false
enable_math = true
enable_site_search = true # default: false
author = "Okulus Dev" # default: no author `meta` tag
color_scheme = "dark" # "light" or "dark"

[params.list_layout]
enable_group_by_year = false # default: true
enable_show_date = true # default: true
enable_pagination = true # default: false

[menu]
[[menu.main]]
name = 'Статьи'
pageRef = '/'
weight = 10
[[menu.main]]
name = 'Теги'
pageRef = '/tags'
weight = 20
[[menu.main]]
name = 'Категории'
pageRef = '/categories'
weight = 30

[[menu.navbar]]
identifier = "tags"
name = "Теги"
title = "Теги"
url = "/tags/"
weight = 100

[[menu.navbar]]
identifier = "categories"
name = "Категории"
title = "Категории"
url = "/categories/"
weight = -100

[[menu.navbar]]
identifier = "posts"
name = "Статьи"
title = "Статьи"
url = "/post/"
weight = 80